services:
    proxy:
        container_name: proxy
        build:
            context: ./proxy
            args:
                - ROOT_DOMAIN=${PROXY_ROOT_DOMAIN}
                - SSL_CERTIFICATE=${PROXY_SSL_CERTIFICATE}
        environment:
            - ROOT_DOMAIN=${PROXY_ROOT_DOMAIN}
            - SSL_CERTIFICATE=${PROXY_SSL_CERTIFICATE}
        ports:
            - 80:80
            - 443:443
        networks:
            - public
    mariadb:
        container_name: mariadb
        build:
            context: ./mariadb
        restart: always
        environment:
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_USER=${MARIADB_DATABASE_USER}
            - MARIADB_PASSWORD=${MARIADB_DATABASE_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${MARIADB_DATABASE_ROOT_PASSWORD}
            - USE_PORT_MAPPING=${MARIADB_USE_PORT_MAPPING}
        ports: 
            - 3306:3306
        volumes:
            - ./mariadb/data:/var/lib/mysql
        networks:
            - private
    workbench-api:
        container_name: workbench-api
        build:
            context: ./workbench-api
        ports:
            - 8080:8080
        networks:
            - public
            - private
networks:
    public:
        driver: bridge
    private:
        driver: bridge