services:
    proxy:
        container_name: proxy
        build:
            context: ./proxy
            args:
                - ROOT_DOMAIN=${PROXY_ROOT_DOMAIN}
                - SSL_CERTIFICATE=${PROXY_SSL_CERTIFICATE}
        environment:
            - ROOT_DOMAIN=${PROXY_ROOT_DOMAIN}
            - SSL_CERTIFICATE=${PROXY_SSL_CERTIFICATE}
        ports:
            - 80:80
            - 443:443
        networks:
            - web
    mariadb:
        container_name: mariadb
        build:
            context: ./mariadb
        restart: always
        environment:
            - MYSQL_USER=${MARIADB_DATABASE_USER}
            - MYSQL_PASSWORD=${MARIADB_DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MARIADB_DATABASE_ROOT_PASSWORD}
        # 컨테이너에서만 통신
        # ports: 
        #    - 3306:3306
        volumes:
            - ./mariadb/data:/var/lib/mysql
        networks:
            - database
    workbench-api:
        container_name: workbench-api
        build:
            context: ./workbench-api
        ports:
            - 8080:8080
        networks:
            - web
            - database
networks:
    web:
        driver: bridge
    database:
        driver: bridge