version: '3.8'
services:
    was:
        container_name: was
        build:
            context: ./was
        restart: always
        networks:
            - workbench-cloud
        ports:
            - 8080:${WAS_PORT}
    rdb:
        container_name: rdb
        build:
            context: ./rdb
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./rdb/data:/var/lib/mysql
        networks:
            - workbench-cloud

networks:
    workbench-cloud: