version: '3.8'
services:
    proxy:
        container_name: proxy
        build:
            context: ./proxy
        ports:
            - 80:80
            - 443:443
        networks:
            - web
    mariadb:
        container_name: mariadb
        build:
            context: ./mariadb
        restart: always
        environment:
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./mariadb/data:/var/lib/mysql
        networks:
            - database
    workbench-api:
        container_name: workbench-api
        build:
            context: ./workbench-api
        ports:
            - 8080:8080
        networks:
            - web
            - database
networks:
    web:
        driver: bridge
    database:
        driver: bridge